from dotenv import load_dotenv
import os

load_dotenv()

CLIENT_ID = os.getenv("INOREADER_CLIENT_ID")
CLIENT_SECRET = os.getenv("INOREADER_CLIENT_SECRET")
REFRESH_TOKEN = os.getenv("INOREADER_REFRESH_TOKEN")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
TELEGRAM_BOT_TOKEN_AI_NEWS = os.getenv("TELEGRAM_BOT_TOKEN_AI_NEWS")
TELEGRAM_CHAT_ID_AI_NEWS = os.getenv("TELEGRAM_CHAT_ID_AI_NEWS")
TELEGRAM_BOT_TOKEN_TECH_STOCK_NEWS = os.getenv("TELEGRAM_BOT_TOKEN_TECH_STOCK_NEWS")
TELEGRAM_CHAT_ID_TECH_STOCK_NEWS = os.getenv("TELEGRAM_CHAT_ID_TECH_STOCK_NEWS")
SERVICE_ACCOUNT_FILE = 'ai-news-sheet-access.json'
